# Medical research in the 21st century

- biology was a science with sparse, often only qualitative data
- now: quantitative data production ~ high energy physics or astronomy but more heterogeneous and complex

"Heterogeneous data are all alike; all heterogeneous data are heterogeneous in their own way." The Anna Karenina priciple

```{r setup, include = FALSE}
library(rentrez)
```

## History
- couple of experimental datapoints, small literature
- hypothesis testing paradigm by R.A. Fisher (1930s)
- iterative approach by Tukey (1977)
- "large p, small n problem": small data point but many features, example: gene expression data set for 10 patients (n = 10) but 20.000 gens (p = 20.000)




## High-throughput technologies in biology
- include a diagram of pubmed publication increase over time
- different statistic neede to the new technologies 
- nice image needed: how changed the data volume from pcr to pcr-array to microarray to mRNA-seq to scRNA-seq
- central dogma: steps and omics


## Introduction to some moder technologies:

### 1. PCR and PCR-array
- link to a nice, high impact paper from the recent couple of years: 

### 2. microarray
- link to a nice, high impact paper from the recent couple of years:

### 3. mRNA-seq
- link to a nice, high impact paper from the recent couple of years:

### 4. scRNA-seq
- link to a nice, high impact paper from the recent couple of years:

### 5. genome sequencing
- link to a nice, high impact paper from the recent couple of years:

### 6. GWAS
- link to a nice, high impact paper from the recent couple of years:

### 7. text mining
- link to a nice, high impact paper from the recent couple of years:

### 8. proteomisc
- link to a nice, high impact paper from the recent couple of years:

### 9. lipidomics
- link to a nice, high impact paper from the recent couple of years:


