# R language

#### R as a calculator
```{r}
1 + 1
```

```{r}
1/2
```

```{r}
log(2)
```

```{r}
log(2, base = 10)
```

#### Get help
```{r}
?log
```

#### Error massage
```{r error = T}
log('a')
```

```{r error = T}
temperature F <- 100
```

#### Logical operations
```{r}
1 == 2
```

```{r}
1 != 2
```

```{r}
1 > 2
```

```{r}
2 >= 2
```

#### Assignement
```{r}
x <- 5
y <- 10
x
y
```

```{r}
(x <- 1/2)
log(x)
```

#### Vectors and vectorised operations
```{r}
a <- c(1, 2, 3)
b <- c(1:5)
a
b
```

```{r}
(a1 <- a + 1)
a1
```

#### Install packages: 
- https://journal.r-project.org/archive/2018/RJ-2018-058/index.html

1. CRAN
```{r eval = F}
utils::install.packages('tidyverse')
```

2. Bioconductor
```{r eval = F}
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install('biomaRt')
```

3. GitHub
```{r eval = F}
if(!requireNamespace('devtools', quietly = TRUE))
   install.packages('devtools')

devtools::install_github("Displayr/flipPlots")
```

#### Find packages: 
- sos package
```{r eval = F}
install.packages('sos')
library(sos)
```

#### Commenting

```{r eval = F}
#best package
library(tidyverse)
```


